name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Create ZIP archive
      run: zip -qq -r ./tricount.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp ./tricount.zip s3://tricount-bucket00/tricount.zip

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name tricount-codeDeploy \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name group1 \
          --s3-location bucket=tricount-bucket00,bundleType=zip,key=tricount.zip
